### PR TITLE
WIP: Add checking twitter following status api

### PR DESCRIPTION
**Pull request by chenzongxiong**

### CODE REVIEW

**Comment by geastwood** [comment]
Where is this route or endpoint being used?

**Comment by chenzongxiong** [comment]
> Where is this route or endpoint being used?

We need this API to help us detect the potential errors during Twitter verification.

**Comment by chenzongxiong** [comment]
This PR shouldn't be merged at this moment!

**Comment by chenzongxiong** [comment]
Useless and stale now.

**Pull request closed without merging**
